### ISSUE TITLE
should `Route` objects catch all errors?

### ISSUE THREAD

**Issue by samandmoore** [Betterment/backbone.blazer#2]
decide if the error method on Route objects should be called given ALL types of errors that could arise when processing a route. i.e. should they be called when there is a view error? undefined method error? etc. is it a try/catch kind of thing?

**Comment by jmileham** [comment]
I feel like there's value in handling errors for the `prepare` function, but if the router is capable of handling errors from the execution, devs may start using it for things that they shouldn't, and end up with, e.g. views that can't be rendered outside of the context of a specific route which has the magic error handling bits in it.

**Comment by jamesplease** [comment]
Ember's solution is [an error substate](http://emberjs.com/guides/routing/loading-and-error-substates/#toc_code-error-code-substates) for each state, which works pretty well. Because this router is not a state machine, you can't get **quite** the same effect, but their implementation could serve as inspiration.

**Comment by samandmoore** [comment]
keeping it the way it is for now. routes will be able to handle rejections from the prepare method.
